#!/usr/bin/env python3
"""Inline local styles, scripts and the logo into one offline HTML file. Python 3.9+."""
from pathlib import Path
import argparse
import base64
import json
import re


def build(destination: Path) -> Path:
    root = Path(__file__).resolve().parent
    release = json.loads((root / 'desktop/release.json').read_text(encoding='utf-8'))
    for field in ('version', 'shellVersion', 'minimumShellVersion'):
        if not re.fullmatch(r'(0|[1-9][0-9]{0,5})\.(0|[1-9][0-9]{0,5})\.(0|[1-9][0-9]{0,5})', release[field]):
            raise ValueError('Invalid desktop release version: ' + field)
    # Generated from one source of truth, for both file:// and HTTP pages.
    (root / 'desktop-version.js').write_text(
        '// Generated by build.py from desktop/release.json.\nwindow.ZhixiangRelease = Object.freeze(' +
        json.dumps(release, ensure_ascii=False).replace('<', '\\u003c') + ');\n', encoding='utf-8')
    modules = json.loads((root / 'models/manifest.json').read_text(encoding='utf-8'))
    if len(set(modules)) != len(modules) or any(not re.fullmatch(r'[a-z][a-z0-9-]*', name) for name in modules):
        raise ValueError('Invalid or duplicate model manifest entry')
    scripts = ['model-registry.js', 'geometry.js', 'physics.js']
    if (root / 'models/shared.js').is_file():
        scripts.append('models/shared.js')
    scripts += ['models/' + name + '.js' for name in modules]
    scripts += ['vendor/qr.js', 'sharing.js', 'accessibility.js', 'chart-export.js', 'desktop-version.js', 'desktop-ui.js', 'question-matcher.js', 'question-ui.js', 'app.js']
    index = root / 'index.html'
    html = index.read_text(encoding='utf-8')
    block = '<!-- scripts:start -->\n' + '\n'.join('<script src="' + name + '"></script>' for name in scripts) + '\n<!-- scripts:end -->'
    if '<!-- scripts:start -->' not in html:
        html = re.sub(r'<script src="geometry\.js[^>]*></script>\s*<script src="physics\.js[^>]*></script>\s*<script src="app\.js[^>]*></script>', block, html)
    else:
        html = re.sub(r'<!-- scripts:start -->[\s\S]*?<!-- scripts:end -->', lambda _: block, html)
    if html != index.read_text(encoding='utf-8'):
        index.write_text(html, encoding='utf-8')
    stylesheet = (root / 'styles.css').read_text(encoding='utf-8')
    # Only the navigation-sized asset is embedded; assets/original is archival.
    logo = base64.b64encode((root / 'assets/zhixiang-logo.png').read_bytes()).decode('ascii')
    stylesheet = stylesheet.replace(
        'url("assets/zhixiang-logo.png")',
        f'url("data:image/png;base64,{logo}")',
    )
    html = re.sub(
        r'<link rel="stylesheet" href="styles\.css(?:\?[^\"]*)?">',
        lambda _: '<style>\n' + stylesheet + '\n</style>',
        html,
    )
    for filename in scripts:
        source = (root / filename).read_text(encoding='utf-8')
        if '</script>' in source.lower():
            raise ValueError(f'{filename} contains a closing script tag; escape it before inlining.')
        html = re.sub(
            rf'<script src="{re.escape(filename)}(?:\?[^\"]*)?"></script>',
            lambda _: '<script>\n' + source + '\n</script>',
            html,
        )
    support_qr = root / 'assets' / 'support-qr.jpg'
    if support_qr.is_file():
        qr = base64.b64encode(support_qr.read_bytes()).decode('ascii')
        html = html.replace('assets/support-qr.jpg', f'data:image/jpeg;base64,{qr}')
    else:
        html = html.replace('assets/support-qr.jpg', '')
    html = html.replace('</head>', '<!--\n' + (root / 'vendor/QR-LICENSE.txt').read_text(encoding='utf-8').replace('--', '—') + '\n-->\n</head>')
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(html, encoding='utf-8')
    return destination


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parent / 'standalone.html')
    args = parser.parse_args()
    result = build(args.output)
    print(f'Built {result} ({result.stat().st_size:,} bytes)')
