/* Deterministic question parsing, unit conversion and strict model-bound checks. */
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const q = require('../question-matcher.js');
const results = [];
function check(name, passed, details) {
  results.push({name, passed: Boolean(passed), details});
  console.log(`${passed ? 'PASS' : 'FAIL'} ${name}${passed ? '' : ' ' + JSON.stringify(details)}`);
}
const close = (a, b, tol = 1e-11) => Number.isFinite(a) && Math.abs(a - b) < tol;
function matched(text, id, expected) {
  const r = q.analyze(text), v = q.validate(r.typeId, r.values);
  return r.typeId === id && !r.issues.length && v.ok && Object.entries(expected).every(([k, x]) => typeof x === 'number' ? close(v.params[k], x) : v.params[k] === x);
}
function rejected(text, type = 'auto') { const r = q.analyze(text, type); return Boolean(r.issues.length) || !q.validate(r.typeId, r.values).ok; }
check('API保留四种旧题型并增加六种大学题型', q.types.length === 10 && q.types.filter(t=>!t.university).length === 4 && q.types.every(t => t.id === t.modelId && t.fields.length && t.example && t.scope));
check('浏览器UMD暴露相同API', (() => {const s = {window:{}}; vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../question-matcher.js'), 'utf8'), s); return s.window.ZhixiangQuestions.types.length === 4;})());
for (const t of q.types.filter(t=>!t.university)) {
  const r = q.analyze(t.example), v = q.validate(r.typeId, r.values);
  check(`内置${t.title}例题完整可映射`, r.typeId === t.id && !r.issues.length && v.ok, {r,v});
  check(`${t.title}每个提取字段有来源`, Object.keys(r.values).every(k => typeof r.sources[k] === 'string' && r.sources[k].length > 0));
}
check('透镜厘米条件', matched('凸透镜焦距10cm，物距30cm，求像距。', 'lens', {kind:'convex',focal:10,objectDistance:30}));
check('透镜米换算为厘米', matched('凸透镜焦距0.1m，物距0.3米，求像距。', 'lens', {focal:10,objectDistance:30}));
check('大小写单位一致换算后再验证范围', (()=>{const r=q.analyze('凸透镜焦距1M，物距2M，求像距。');return r.values.focal===100&&r.values.objectDistance===200&&!q.validate('lens',r.values).ok;})());
check('大写CM与KG单位正确读取', matched('凸透镜焦距10CM，物距30CM，求像距。','lens',{focal:10,objectDistance:30})&&matched('碰撞 m1=1KG,m2=2000G,u1=3m/s,u2=-1m/s,e=1。','collision',{mass1:1,mass2:2,e:1}));
check('凹透镜负焦距只取明确类型下的大小', matched('凹透镜焦距-10cm，物距30cm，求像距。', 'lens', {kind:'concave',focal:10,objectDistance:30}));
check('正透镜不吞掉负焦距', rejected('凸透镜焦距-10cm，物距30cm。'));
check('焦距处保留无有限成像提示', q.validate('lens',{kind:'convex',focal:10,objectDistance:10}).notes.some(n => n.includes('u=f')));
check('物高不伪装成已识别题设', (()=>{const r=q.analyze('凸透镜焦距10cm，物距30cm。'), v=q.validate('lens',r.values);return !Object.hasOwn(v.params,'objectHeight')&&v.notes.some(n=>n.includes('示意'));})());
check('含物高题第一版明确拒绝', rejected('凸透镜焦距10cm，物距30cm，物高2cm，求像高。'));
check('缺焦距不填默认10', (()=>{const r=q.analyze('凸透镜物距30cm。');return !Object.hasOwn(r.values,'focal')&&!q.validate('lens',r.values).ok;})());
check('冲突数值阻止进入', q.analyze('凸透镜焦距10cm，焦距12cm，物距30cm。').issues.length > 0);
check('反求透镜物距拒绝', rejected('凸透镜焦距10cm，像距30cm，求物距。'));
check('像距离透镜不当作物距', (()=>{const r=q.analyze('凸透镜焦距10cm，像距离透镜30cm，求物体位置。');return !Object.hasOwn(r.values,'objectDistance')&&r.issues.length>0;})());
check('模糊距透镜描述不编造物体身份', !Object.hasOwn(q.analyze('凸透镜焦距10cm，距透镜30cm。').values,'objectDistance'));
check('两个透镜拒绝', rejected('两个透镜组成透镜组，焦距10cm，物距30cm。'));
check('理想平抛正向值', matched('物体从20m高处以10m/s水平抛出，忽略空气阻力，g=10m/s²。', 'projectile',{height:20,v:10,g:10,angle:0,motionMode:'ideal'}));
check('平抛数值单位与高处之间可有空格', matched('物体从 20 m 高处，以 10 m/s 的初速度水平抛出。忽略空气阻力，g=10 m/s²，求落地时间和水平位移。','projectile',{height:20,v:10,g:10,angle:0,motionMode:'ideal'}));
check('平抛单位与的高处之间可有空格', matched('物体从 15 米 的 高处，以 10 m/s 水平抛出，忽略空气阻力，g=9.8 m/s²。','projectile',{height:15,v:10,g:9.8,angle:0,motionMode:'ideal'}));
check('平抛厘米与每秒厘米换算', matched('平抛，初始高度1500cm，初速度1000cm/s，g=980cm/s²，不计空气阻力。','projectile',{height:15,v:10,g:9.8}));
check('平抛g不从默认值补齐', (()=>{const r=q.analyze('平抛，高度10m，速度10m/s。');return !Object.hasOwn(r.values,'g')&&!q.validate('projectile',r.values).ok;})());
check('阻力假设未写需明确确认', q.analyze('平抛，高度10m，速度10m/s，g=10m/s²。').warnings.some(n=>n.includes('阻力')));
check('忽略阻力不会被误判含阻力', !q.analyze('平抛，高度10m，速度10m/s，g=10m/s²，忽略空气阻力。').issues.length);
check('含阻力题拒绝', rejected('平抛，高度10m，速度10m/s，g=10m/s²，考虑空气阻力。'));
check('忽略阻力的否定句必须拒绝', ['不能忽略空气阻力','不可忽略空气阻力','不应忽略阻力','空气阻力不可忽略'].every(condition=>q.analyze(`平抛，高度10m，初速度10m/s，g=10m/s²，${condition}。`).issues.length>0));
check('斜面与多物体复合题拒绝', ['物体水平抛出后落到斜面。','两个小球水平抛出，求相遇。','斜抛，初速度10m/s，仰角30°。'].every(t=>rejected(t)));
check('反求初速度拒绝', rejected('平抛，高度10m，g=10m/s²，飞行2s，求初速度。'));
check('未说明高度的远处距离不当作初始高度', !Object.hasOwn(q.analyze('物体从20m远处以10m/s水平抛出，g=10m/s²。').values,'height'));
check('给定末速度不作为初速度使用', rejected('平抛，高度10m，初速度10m/s，落地速度20m/s，g=10m/s²。'));
check('给定中途速度必须硬拒绝', q.analyze('物体从20m高处水平抛出，g=10m/s²，经过1s速度10m/s，求落地时间。').issues.length>0);
check('给定时刻t与速度硬拒绝', q.analyze('平抛，高度20m，g=10m/s²，t=1s时速度为10m/s，求落地时间。').issues.length>0);
check('超界高度不限制为20', (()=>{const r=q.analyze('平抛，高度50m，速度10m/s，g=10m/s²。');return r.values.height===50&&!q.validate('projectile',r.values).ok;})());
check('零高度明确显示边界', q.validate('projectile',{height:0,v:10,g:10}).notes.some(n=>n.includes('t=0')));
check('带下标一维碰撞参数', matched('一维弹性碰撞，m₁=1kg，m₂=2kg，u₁=3m/s，u₂=-1m/s。','collision',{mass1:1,mass2:2,u1:3,u2:-1,e:1}));
check('甲乙物体和克换算', matched('甲球质量500g，初速度向右3m/s；乙球质量1000g，初速度向左1m/s。弹性碰撞。','collision',{mass1:.5,mass2:1,u1:3,u2:-1,e:1}));
check('完全非弹性不会错误识别e=1', matched('碰撞：m1=1kg，m2=2kg，u1=3m/s，u2=0m/s，完全非弹性碰撞。','collision',{e:0}));
check('粘连对应e=0', matched('碰撞：m1=1kg，m2=2kg，u1=3m/s，u2=0m/s，碰后粘在一起。','collision',{e:0}));
check('显式恢复系数小数', matched('碰撞：m1=1kg，m2=2kg，u1=3m/s，u2=-1m/s，恢复系数0.6。','collision',{e:.6}));
check('恢复系数分数完整读取不取分子', matched('碰撞 m1=1kg,m2=2kg,u1=3m/s,u2=-1m/s,恢复系数1/2，求碰后速度。','collision',{e:.5}));
check('恢复系数带空格分数', matched('碰撞 m1=1kg,m2=2kg,u1=3m/s,u2=-1m/s,e= 1 / 2，求碰后速度。','collision',{e:.5}));
check('恢复系数表达式不半匹配', ['1/2/3','1+1','1/0','0.5kg','1^2'].every(e=>q.analyze(`碰撞 m1=1kg,m2=2kg,u1=3m/s,u2=-1m/s,e=${e}，求碰后速度。`).issues.length>0));
check('带空格及百分比恢复系数不取前半项', ['0.5+0.5','50%','0.5 + 0.5','1 / 2 / 3','1 / 0'].every(e=>q.analyze(`碰撞 m1=1kg,m2=2kg,u1=3m/s,u2=-1m/s,e=${e}，求碰后速度。`).issues.length>0));
check('否定粘连不能设置e为零', (()=>{const r=q.analyze('碰撞 m1=1kg,m2=2kg,u1=3m/s,u2=-1m/s。两球没有粘在一起，求碰后速度。');return r.issues.length>0&&!Object.hasOwn(r.values,'e');})());
check('否定弹性不能设置e为一', ['不是弹性碰撞','并非弹性碰撞','未发生弹性碰撞'].every(condition=>{const r=q.analyze(`碰撞 m1=1kg,m2=2kg,u1=3m/s,u2=-1m/s，${condition}，求碰后速度。`);return r.issues.length>0&&!Object.hasOwn(r.values,'e');}));
check('碰后速度和静止不得当初态', q.analyze('球1质量1kg，碰后速度向右3m/s；球2质量2kg，碰后静止。弹性碰撞，求碰前动量。').issues.length>0);
check('单给碰后状态也硬拒绝', q.analyze('球1质量1kg，碰撞后速度向右3m/s；球2质量2kg，碰后静止。弹性碰撞。').issues.length>0);
check('正常求碰后速度不被当成已知条件', matched('弹性碰撞：m1=1kg，m2=2kg，u1=3m/s，u2=-1m/s，求碰后速度。','collision',{u1:3,u2:-1,e:1}));
check('未说明碰撞类型不得默认弹性', (()=>{const r=q.analyze('碰撞：m1=1kg，m2=2kg，u1=3m/s，u2=0m/s。');return !Object.hasOwn(r.values,'e')&&!q.validate('collision',r.values).ok;})());
check('仅非弹性不足以确定e', !Object.hasOwn(q.analyze('非弹性碰撞：m1=1kg，m2=2kg，u1=3m/s，u2=0m/s。').values,'e'));
check('方向不确定不编造正号', (()=>{const r=q.analyze('球1质量1kg，初速度3m/s；球2质量2kg，初速度1m/s，弹性碰撞。');return !Object.hasOwn(r.values,'u1')&&!Object.hasOwn(r.values,'u2');})());
check('静止物体可识别为零速度', matched('球1质量1kg，速度向右3m/s；球2质量2kg，初始静止。弹性碰撞。','collision',{u2:0}));
check('球1在右不得悄悄反转编号', rejected('球1在右，质量1kg，速度向左3m/s；球2在左，质量2kg，速度向右1m/s。弹性碰撞。'));
check('碰撞不会相遇阻止无意义演示', !q.validate('collision',{mass1:1,mass2:2,u1:-1,u2:1,e:1}).ok);
check('碰撞相距条件不套用固定间距', rejected('弹性碰撞：m1=1kg，m2=2kg，u1=3m/s，u2=-1m/s，两球相距10m，求碰撞时间。'));
check('向左为正必须先转换', rejected('弹性碰撞，向左为正：m1=1kg，m2=2kg，u1=3m/s，u2=-1m/s。'));
check('一维碰撞默认空间位置标示为演示', q.validate('collision',{mass1:1,mass2:2,u1:3,u2:-1,e:1}).notes.some(n=>n.includes('演示设置')));
check('二次函数一般式配方', matched('y=2x²-4x+1，求顶点。','parabola',{a:2,h:1,k:-1}));
check('二次函数顶点式', matched('二次函数y=-2(x+1)²+3，求顶点。','parabola',{a:-2,h:-1,k:3}));
check('f(x)与省略一系数', matched('f(x)=-(x-2)^2+1，求顶点。','parabola',{a:-1,h:2,k:1}));
check('分数系数受限解析', matched('y=1/2x²-x+1，求顶点。','parabola',{a:.5,h:1,k:.5}));
check('全角字符、空格和Unicode负号', matched('ｙ＝２ｘ² − ４ｘ ＋ １，求顶点。','parabola',{a:2,h:1,k:-1}));
check('不吞掉不支持的函数项', ['y=x²+sin(x)，求顶点。','y=x²+1/x，求顶点。','y=x²+x³，求顶点。','y=x²加3，求顶点。','y=x²+√x，求顶点。'].every(t=>rejected(t,'parabola')));
check('不吞掉损坏的运算符', ['y=x²++1，求顶点。','y=x²--1，求顶点。','y=x²+，求顶点。','y=2**x²，求顶点。'].every(t=>rejected(t)));
check('二次项为零不伪装抛物线', rejected('y=0x²+2x+1，求顶点。')&&!q.validate('parabola',{a:0,h:0,k:1}).ok);
check('除零和无穷系数拒绝', ['y=1/0x²+1，求顶点。','y=Infinity*x²，求顶点。'].every(t=>rejected(t,'parabola')));
check('不支持多函数和附加约束', ['y=x²，y=-x²，求交点。','y=x²，定义域为[0,1]。','y=x²，求与直线的交点。','已知二次函数经过三点，求函数解析式。'].every(t=>rejected(t,'parabola')));
check('附加定义域符号不能静默忽略', ['y=x²，x≥0。','y=x²，x∈[0,1]。','y=x²，0<x<1。'].every(t=>rejected(t,'parabola')));
check('中文定义域附加约束必须拒绝', ['y=x²，当x大于1时，求最小值。','y=x²，x 不小于1，求顶点。','y=x²，自变量属于正数，求顶点。'].every(t=>q.analyze(t,'parabola').issues.length>0));
check('超界系数保留原始值后拒绝', (()=>{const r=q.analyze('y=10x²，求顶点。');return r.values.a===10&&!q.validate('parabola',r.values).ok;})());
check('不直接执行任意代码', ['y=x²;eval(alert(1))','<script>alert(1)</script> y=x²','y=x²+require("fs")','y=(()=>1)()'].every(t=>rejected(t,'parabola')));
check('混合题型阻止打开', q.analyze('凸透镜焦距10cm，物距30cm。另一个物体从10m高度平抛，速度10m/s，g=10m/s²。').issues.length>0);
check('手动选型与题意冲突拒绝', q.analyze('凸透镜焦距10cm，物距30cm。','projectile').issues.length>0);
check('编号多题拒绝', q.analyze('1. 凸透镜焦距10cm，物距30cm。\n2. 凸透镜焦距15cm，物距40cm。').issues.length>0);
check('同行多个小问明确拒绝', q.analyze('凸透镜焦距10cm，物距30cm。（1）求像距；（2）改变物距。').issues.length>0);
check('图片引用提示仅识别文字', q.analyze('如图，凸透镜焦距10cm，物距30cm，求像距。').warnings.some(n=>n.includes('图示')));
check('无匹配不猜题型', q.analyze('求一个三角形的面积。').typeId===null);
check('空字符串和非字符串输入稳定拒绝', ['', ' ', null, 123, {}].every(t=>q.analyze(t).issues.length>0));
check('超长题目明确拒绝', q.analyze('平抛'+ '字'.repeat(q.MAX_TEXT_LENGTH)).issues.some(n=>n.includes('4000')));
check('未知题型和不合法条件对象拒绝', !q.validate('unknown',{}).ok&&!q.validate('lens',null).ok&&!q.validate('lens',[]).ok);
check('严格要求有限Number不隐式转换', ['10', NaN, Infinity, -Infinity, null, undefined, true].every(x=>!q.validate('lens',{kind:'convex',focal:x,objectDistance:30}).ok));
check('不读取原型链题设', !q.validate('lens',Object.create({kind:'convex',focal:10,objectDistance:30})).ok);
check('不允许任意select值', !q.validate('lens',{kind:'constructor',focal:10,objectDistance:30}).ok);
check('额外字段不能注入模型', (()=>{const r=q.validate('lens',{kind:'convex',focal:10,objectDistance:30,objectHeight:999,onload:'evil'});return r.ok&&!Object.hasOwn(r.params,'objectHeight')&&!Object.hasOwn(r.params,'onload');})());
check('保留4位以后合法精度', (()=>{const x=10.1234567890123,r=q.validate('lens',{kind:'convex',focal:x,objectDistance:30.987654321});return r.ok&&r.params.focal===x&&r.params.objectDistance===30.987654321;})());
check('所有数值边界均严格检查不夹取', q.types.filter(t=>!t.university).every(t=>t.fields.filter(f=>f.type==='number').every(f=>{const base=q.analyze(t.example).values;return !q.validate(t.id,{...base,[f.key]:f.min-1}).ok&&!q.validate(t.id,{...base,[f.key]:f.max+1}).ok;})));
check('解析不修改调用者的条件对象', (()=>{const values={kind:'convex',focal:10,objectDistance:30},before=JSON.stringify(values);q.validate('lens',values);return JSON.stringify(values)===before;})());
let seed=20261006;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32);
let randomQuadratics=true,maxError=0,randomUnits=true;
for(let i=0;i<500;i++){
  const a=(random()>.5?1:-1)*(.2+2.7*random()),h=-3+6*random(),k=-3+7*random(),b=-2*a*h,c=a*h*h+k;
  const sign=n=>n<0?String(n):'+'+n;
  const r=q.analyze(`y=${a}x^2${sign(b)}x${sign(c)}，求顶点。`),v=q.validate('parabola',r.values);
  const err=Math.max(Math.abs(r.values.a-a),Math.abs(r.values.h-h),Math.abs(r.values.k-k));
  maxError=Math.max(maxError,err);randomQuadratics&&=!r.issues.length&&v.ok&&err<1e-11;
  const f=1+19*random(),u=.5+59.5*random();
  randomUnits&&=matched(`凸透镜焦距${f/100}m，物距${u/100}m，求像距。`,'lens',{focal:f,objectDistance:u});
}
check('500组随机二次式配方符合原系数',randomQuadratics,{maxAbsoluteError:maxError});
check('500组随机米厘米转换保留数值',randomUnits);
const out=require('./runtime.cjs').outputDir;
fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,'question-math-results.json'),JSON.stringify({date:new Date().toISOString(),results},null,2));
console.log(`RESULT ${results.filter(r=>r.passed).length}/${results.length}`);
if(results.some(r=>!r.passed))process.exitCode=1;
