const fs=require('node:fs'),path=require('node:path');
const {chromium}=require('./runtime.cjs').loadPlaywright();
const root=path.resolve(__dirname,'..'),out=require('./runtime.cjs').outputDir;fs.mkdirSync(out,{recursive:true});let browser;
const results=[],errors=[],remote=[];const check=(name,passed,details)=>{results.push({name,passed:!!passed,details});console.log(`${passed?'PASS':'FAIL'} ${name}${passed?'':' '+JSON.stringify(details)}`);};
(async()=>{
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith((require('./runtime.cjs').baseURL + '/')))remote.push(r.url());});
 await page.goto((require('./runtime.cjs').baseURL + '/index.html?qa=extensions'));
 const draw=async()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const open=async id=>{await page.evaluate(id=>openModel(id),id);await draw();};
 const fill=async(key,value)=>{await page.locator('#number-'+key).fill(String(value));await page.locator('#number-'+key).press('Tab');await draw();};
 const capture=async name=>{await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo({top:0,behavior:'instant'});});await draw();await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});};
 const snapshot=()=>page.evaluate(()=>JSON.stringify([state.time,state.theta,state.omega,state.idealTheta,state.idealOmega,state.oscillator,state.pendulumHistory,state.springHistory]));
 check('保留 21 个模型并在折射旁新增透镜；共 28 个',await page.locator('.model-card').count()=== 28&&await page.evaluate(()=>MODELS.findIndex(m=>m.id==='lens')===MODELS.findIndex(m=>m.id==='refraction')+1));
 await page.locator('#searchInput').fill('三视图');check('三视图可以搜索到现有常见几何体',await page.locator('[data-open=solids]').count()===1);
 await open('solids');await page.locator('#geo-study').selectOption('views');check('新增观察内容放在原参数栏，保留工具栏',await page.locator('.geo-view').count()===4&&await page.locator('#solidSelect option').count()===8);
 for(const shape of['cube','cuboid','prism','tetra','pyramid','cylinder','cone','sphere']){await page.locator('#solidSelect').selectOption(shape);await draw();check(shape+' 三视图可渲染',await page.evaluate(()=>stageInfo.study==='views'&&!/NaN|Infinity/.test($('#metrics').innerText)));}
 await page.locator('#solidSelect').selectOption('prism');await capture('three-views-desktop');
 const projections=await page.evaluate(()=>JSON.stringify(['front','top','side'].map(v=>geoOrthographic(solidMesh(state.p),v))));await page.locator('[data-geo-view=top]').click();await draw();check('切换相机不改变三幅固定投影',await page.evaluate(v=>JSON.stringify(['front','top','side'].map(v=>geoOrthographic(solidMesh(state.p),v)))===v,projections));
 await page.locator('#geo-study').selectOption('restore');check('还原明确限定样例库',await page.locator('#formulaCaption').innerText().then(t=>t.includes('8 种样例')));
 const circleTop=await page.evaluate(()=>geoProjectionBank().options.top.find(o=>o.signature===geoProjectionBank().samples.find(q=>q.id==='cylinder').views.top.signature).id);
 await page.locator('#geo-restoreFront').selectOption('cube');await page.locator('#geo-restoreTop').selectOption(circleTop);await page.locator('#geo-restoreSide').selectOption('cube');await draw();check('正方形、圆、正方形选回圆柱',await page.locator('#formula').innerText().then(t=>t.includes('圆柱')));
 await capture('three-views-reconstruction');await page.locator('#geo-restoreFront').selectOption('sphere');await draw();check('不相容三视图不伪造立体',await page.locator('#formula').innerText().then(t=>t.includes('没有匹配')));
 await open('solids');await page.locator('#geo-study').selectOption('angles');check('两棱的空间点积过程显示完整',await page.locator('#formula').innerText().then(t=>t.includes('u·v=')&&t.includes('90°')));
 await page.locator('#geo-angleKind').selectOption('line-plane');await page.locator('#geo-edge1').selectOption('0:4');await page.locator('#geo-face1').selectOption('0');check('选择棱与平面实时得到 90°',await page.locator('#formula').innerText().then(t=>t.includes('sin α=')&&t.includes('90°')));
 await page.locator('#geo-angleKind').selectOption('dihedral');await page.locator('#geo-face1').selectOption('0');await page.locator('#geo-face2').selectOption('1');check('相对面只给锐夹角，不伪造二面角',await page.locator('#metrics').innerText().then(t=>t.includes('不定义')));
 await page.locator('#solidSelect').selectOption('pyramid');await page.locator('#geo-face1').selectOption('1');await page.locator('#geo-face2').selectOption('2');check('正棱锥允许钝内二面角',await page.evaluate(()=>geoAngleData(state.model,state.p).angle>90));await capture('dihedral-desktop');
 await page.locator('#geo-study').selectOption('vectors');await page.locator('#geo-vectorFrom').selectOption('0');await page.locator('#geo-vectorTo').selectOption('4');check('顶点坐标、向量及模显示',await page.locator('#formula').innerText().then(t=>t.includes('√(')&&t.includes('cm')));
 await page.locator('#geo-vectorTo').selectOption('0');check('零向量显示模 0 与方向未定义',await page.locator('#metrics').innerText().then(t=>t.includes('方向未定义')));
 await open('sections');await page.locator('#geo-study').selectOption('angles');await page.locator('#geo-angleKind').selectOption('line-plane');await page.locator('#geo-face1').selectOption('cut');check('截平面可参与线面角',await page.locator('#metrics').innerText().then(t=>t.includes('截平面')));
 await fill('offset',100);check('截面退化后面选择与实际参数同步回退',await page.locator('#geo-face1').inputValue()===await page.evaluate(()=>state.p.face1)&&await page.locator('#geo-face1 option[value=cut]').count()===0);
 await fill('offset',0);await page.locator('#geo-study').selectOption('vectors');await page.locator('#geo-vectorTo').selectOption('cut0');check('截面交点可参与坐标与向量',await page.locator('#metrics').innerText().then(t=>t.includes('终点 P')));await capture('section-vectors-desktop');
 // Display toggles must leave motion state untouched, including while paused at a nonzero time.
 await open('projectile');await page.locator('[data-environment][value=compare]').check();await page.locator('#timeline').fill('300');await draw();
 const motion=await page.evaluate(()=>JSON.stringify([state.time,resistedProjectile(state.p).range,projectileAt(state.p,state.time,true)]));let pixels=await page.locator('#simCanvas').evaluate(c=>c.toDataURL());
 for(const key of['showVelocity','showComponents','showStrobe'])await page.locator('[data-motion-toggle='+key+']').uncheck();await draw();
 check('抛体三项显示开关实际改变画面',await page.locator('#simCanvas').evaluate(c=>c.toDataURL())!==pixels);
 check('显示开关不改变抛体时间、轨迹或速度',await page.evaluate(v=>JSON.stringify([state.time,resistedProjectile(state.p).range,projectileAt(state.p,state.time,true)])===v,motion));
 await fill('strobeInterval',.35);check('频闪间隔只改变采样显示，不重置运动',await page.evaluate(v=>JSON.stringify([state.time,resistedProjectile(state.p).range,projectileAt(state.p,state.time,true)])===v,motion));
 for(const key of['showVelocity','showComponents','showStrobe'])await page.locator('[data-motion-toggle='+key+']').check();await capture('projectile-vectors-strobe');
 await open('pendulum');await page.locator('[data-environment][value=compare]').check();await page.evaluate(()=>{for(let i=0;i<600;i++)updateSimulation(1/120);renderReadout();requestDraw();});await draw();
 check('单摆能量图采样时刻与当前求解状态一致',await page.evaluate(()=>{const q=state.pendulumHistory.at(-1),e=pendulumEnergy(state.p,state.theta,state.omega);return q.t===state.time&&q.actual.kinetic===e.kinetic&&q.actual.potential===e.potential&&q.actual.total===e.kinetic+e.potential&&stageInfo.energyTime===state.time;}));
 const pendulumBefore=await snapshot();await page.locator('#energySource').selectOption('ideal');await page.locator('[data-motion-toggle=energyGraph]').uncheck();await page.locator('[data-motion-toggle=energyGraph]').check();check('单摆能量对象和显示开关不改变求解状态',await snapshot()===pendulumBefore);await page.locator('#energySource').selectOption('actual');await capture('pendulum-energy-desktop');
 await page.locator('[data-action=play]').click();await page.waitForFunction(()=>state.time>5.1);await page.locator('[data-action=play]').click();await draw();let frozen=await snapshot(),frozenPixels=await page.locator('#simCanvas').evaluate(c=>c.toDataURL());await page.waitForTimeout(180);check('单摆暂停后时间、积分、能量曲线和画布同时冻结',await snapshot()===frozen&&await page.locator('#simCanvas').evaluate(c=>c.toDataURL())===frozenPixels);
 await open('lens');let lensPixels=await page.locator('#simCanvas').evaluate(c=>c.toDataURL());await page.locator('[data-flag=labels]').uncheck();await draw();check('透镜标注开关实际影响画面，像距不变',await page.locator('#simCanvas').evaluate(c=>c.toDataURL())!==lensPixels&&await page.evaluate(()=>stageInfo.data.v===15));await page.locator('[data-flag=labels]').check();check('透镜默认实像倒立与 cm 符号约定',await page.locator('#metrics').innerText().then(t=>t.includes('15')&&t.includes('实像 · 倒立'))&&await page.locator('#formulaCaption').innerText().then(t=>t.includes('实正虚负')));
 for(const [preset,type] of[['3','虚像 · 正立'],['4','不成有限像'],['5','虚像 · 正立']]){await page.locator('[data-preset="'+preset+'"]').click();await draw();check('透镜边界预设 '+preset,await page.locator('#metrics').innerText().then(t=>t.includes(type)&&!(/NaN|Infinity/.test(t))));}
 check('凹透镜 f<0，像距也为负',await page.evaluate(()=>stageInfo.data.f<0&&stageInfo.data.v<0));await capture('lens-concave-desktop');
 await page.locator('[data-preset="4"]').click();check('u=f 的提示和两条平行出射光',await page.locator('#scienceNotice').innerText().then(t=>t.includes('不能在屏上成像'))&&await page.evaluate(()=>SCIENCE.lensRays(state.p).length===2));
 await page.locator('[data-preset="0"]').click();await page.locator('#simCanvas').scrollIntoViewIfNeeded();await draw();let pos=await page.evaluate(()=>{const r=$('#simCanvas').getBoundingClientRect();return {x:r.left+stageInfo.objectX,y:r.top+stageInfo.objectY};});await page.mouse.move(pos.x,pos.y);await page.mouse.down();await page.mouse.move(pos.x+40,pos.y,{steps:8});await page.mouse.up();await draw();
 check('真实拖动物体改变物距和像距',await page.evaluate(()=>state.p.objectDistance<30&&stageInfo.data.v>15&&state.lensExtentLock===null));const u=await page.evaluate(()=>state.p.objectDistance);await page.locator('#simCanvas').focus();await page.keyboard.press('ArrowLeft');check('物距支持键盘操作',await page.evaluate(u=>Math.abs(state.p.objectDistance-u-.5)<1e-8,u));
 await fill('objectDistance',0);check('透镜拒绝物距为零并保留原值',await page.evaluate(u=>Math.abs(state.p.objectDistance-u-.5)<1e-8,u));await fill('objectDistance',10.0000000001);check('焦点极近处仍有有限读数，超窗有提示',await page.evaluate(()=>Number.isFinite(stageInfo.data.v)&&!stageInfo.data.atFocus));
 await open('spring');check('旧弹簧配置默认使用原理想模型',await page.evaluate(()=>state.p.springMode==='ideal'&&springCurrentData(state.p).x===state.p.amp));
 for(const mode of['under','critical','over','forced']){await page.locator('#springMode').selectOption(mode);await page.evaluate(()=>{for(let i=0;i<120;i++)updateSimulation(.025);renderReadout();requestDraw();});await draw();check(mode+' 模式有同步位移曲线与有限读数',await page.evaluate(()=>Number.isFinite(springCurrentData(state.p).x)&&stageInfo.graphTime===state.time&&state.time>2.99&&!/NaN|Infinity/.test($('#metrics').innerText)));if(mode==='under')await capture('spring-damped-desktop');}
 await fill('driveForce',2);await fill('driveFreq',.9);await page.evaluate(()=>{for(let i=0;i<400;i++)updateSimulation(.025);renderReadout();requestDraw();});await capture('spring-forced-desktop');
 await page.locator('[data-action=play]').click();await page.waitForFunction(()=>state.time>10.1);await page.locator('[data-action=play]').click();await draw();frozen=await snapshot();frozenPixels=await page.locator('#simCanvas').evaluate(c=>c.toDataURL());await page.waitForTimeout(150);check('弹簧暂停后 RK4、时间图和画布同步冻结',await snapshot()===frozen&&await page.locator('#simCanvas').evaluate(c=>c.toDataURL())===frozenPixels);
 await fill('zeta',0);await page.locator('[data-action=spring-resonance]').click();check('零阻尼设为固有频率时明确无有限稳态',await page.locator('#metrics').innerText().then(t=>t.includes('无有限稳态')));await fill('driveForce',0);check('零驱动力共振点仍为零响应',await page.evaluate(()=>SCIENCE.oscillatorResponse(state.p).amplitude===0));
 for(const [id,p] of[['solids',{study:'views',shape:'prism'}],['sections',{study:'vectors',vectorTo:'cut0'}],['solids',{study:'angles',shape:'pyramid',angleKind:'dihedral',face1:'1',face2:'2'}],['pendulum',{motionMode:'compare'}],['lens',{kind:'concave'}],['spring',{springMode:'forced'}]]){
  await page.evaluate(([id,p])=>openModel(id,p),[id,p]);await draw();const numeric=await page.evaluate(()=>JSON.stringify(readout(state.model,state.p).metrics));
  for(const width of[320,390,768,1024,1440]){await page.setViewportSize({width,height:1050});await draw();check(id+' '+(p.study||p.springMode||'')+' '+width+'px 无溢出且数值不变',await page.evaluate(v=>document.documentElement.scrollWidth<=innerWidth+1&&JSON.stringify(readout(state.model,state.p).metrics)===v,numeric));if(width===390)await capture('extensions-'+id+'-'+(p.study||p.springMode||'')+'-mobile');}
 }
 for(const id of['solids','sections','projectile','pendulum','lens','spring']){
  await open(id);if(id==='solids'||id==='sections'){await page.locator('#geo-study').selectOption('angles');await page.locator('#geo-angleKind').selectOption('line-plane');}if(id==='projectile')await page.locator('[data-motion-toggle=showVelocity]').uncheck();if(id==='pendulum'){await page.locator('[data-environment][value=compare]').check();await page.locator('#energySource').selectOption('ideal');}if(id==='lens')await page.locator('#science-kind').selectOption('concave');if(id==='spring'){await page.locator('#springMode').selectOption('forced');await fill('zeta',0);await page.locator('[data-action=spring-resonance]').click();}
  const params=await page.evaluate(()=>JSON.stringify(state.p));await page.locator('[data-action=save]').click();await page.locator('#classTitle').fill(id+' 扩展回归');await page.locator('[data-action=confirm-save]').click();await page.evaluate(()=>showLibrary('classes'));await page.locator('[data-class-open]').first().click();check(id+' 课堂保存恢复新增字段',await page.evaluate(v=>JSON.stringify(state.p)===v,params));
  await page.locator('[data-action=share]').click();const download=page.waitForEvent('download');await page.locator('[data-action=export-config]').click();const file=path.join(out,'extensions-'+id+'-config.json');await(await download).saveAs(file);await page.locator('[data-action=close-dialog]').click();await page.locator('#importFile').setInputFiles(file);await page.locator('[data-action=confirm-import]').click();check(id+' 新字段真实导入导出 version:1',JSON.parse(fs.readFileSync(file)).version===1&&await page.evaluate(v=>JSON.stringify(state.p)===v,params));
  await page.locator('#simCanvas').scrollIntoViewIfNeeded();await page.locator('[data-action=ink]').click();const box=await page.locator('#annotation').boundingBox();await page.mouse.move(box.x+50,box.y+50);await page.mouse.down();await page.mouse.move(box.x+85,box.y+90,{steps:4});await page.mouse.up();check(id+' 板书不改参数',await page.evaluate(v=>state.strokes.length===1&&JSON.stringify(state.p)===v,params));await page.locator('[data-action=ink]').click();
  const image=page.waitForEvent('download');await page.locator('[data-action=screenshot]').click();const imagePath=path.join(out,'extensions-'+id+'-export.png');await(await image).saveAs(imagePath);check(id+' PNG 实际导出',fs.statSync(imagePath).size>25000);
  await page.locator('[data-action=present]').click();check(id+' 大屏可用',await page.locator('body').evaluate(el=>el.classList.contains('presenting')));await page.keyboard.press('Escape');await page.evaluate(()=>exitPresentation());
  await page.locator('[data-action=model-info]').click();check(id+' 模型条件与参考可查看',await page.locator('#dialogBody a').count()>0);await page.locator('[data-action=close-dialog]').click();
 }
 check('旧 v1 文件缺少新增字段时使用明确默认值',await page.evaluate(()=>{const read=(model,params)=>validateImport({app:'zhixiang',version:1,type:'model',model,params}).params;return read('solids',{a:4}).study==='basic'&&read('sections',{a:2}).vectorTo==='6'&&read('projectile',{v:25}).showVelocity&&read('projectile',{v:25}).strobeInterval===.2&&read('pendulum',{length:2}).energyGraph&&read('spring',{mass:2,stiff:10,amp:.7}).springMode==='ideal';}));
 const offline=await context.newPage(),offlineRequests=[];offline.on('pageerror',e=>errors.push(e.message));offline.on('request',r=>{if(/^https?:/.test(r.url()))offlineRequests.push(r.url());});
 for(const [id,p] of[['solids',{study:'restore'}],['sections',{study:'vectors'}],['pendulum',{energyGraph:true}],['lens',{kind:'concave'}],['spring',{springMode:'forced'}]]){await offline.goto('file://'+path.join(root,'standalone.html')+'#'+new URLSearchParams({model:id,params:JSON.stringify(p)}));await offline.waitForFunction(id=>state.model?.id===id&&stageInfo,id);check(id+' 新功能在单文件中离线打开',await offline.evaluate(()=>!!stageInfo&&!/NaN|Infinity/.test($('#metrics').innerText)));}
 check('离线无网络依赖',offlineRequests.length===0,offlineRequests);check('分文件无外部运行请求',remote.length===0,remote);check('浏览器无脚本异常',errors.length===0,errors);
 await browser.close();fs.writeFileSync(path.join(out,'extensions-browser-results.json'),JSON.stringify({date:new Date().toISOString(),results,errors,remote},null,2));console.log(`RESULT ${results.filter(r=>r.passed).length}/${results.length}`);if(results.some(r=>!r.passed))process.exitCode=1;
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
