/* Actual controls, playback, timeline, v1 files, PNG output and offline use. */
const fs=require('node:fs'),path=require('node:path');
const {chromium}=require('./runtime.cjs').loadPlaywright();
const root=path.resolve(__dirname,'..'),out=require('./runtime.cjs').outputDir;fs.mkdirSync(out,{recursive:true});
const results=[],errors=[],remote=[];let browser;
const check=(name,passed,details)=>{results.push({name,passed:!!passed,details});console.log(`${passed?'PASS':'FAIL'} ${name}${passed?'':' '+JSON.stringify(details)}`);};
(async()=>{
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith((require('./runtime.cjs').baseURL + '/')))remote.push(r.url());});
 await page.goto((require('./runtime.cjs').baseURL + '/index.html?qa=collision'));
 check('新增后 22 个模型、物理 12 个',await page.locator('.model-card').count()===22&&await page.locator('[data-category=physics] small').innerText()==='12');
 await page.locator('[data-filter=physics]').click();await page.locator('#gradeFilter').selectOption('高中');await page.locator('#searchInput').fill('动量');
 check('物理、高中和动量搜索可找到新模型',await page.locator('.model-card').count()===1);await page.locator('[data-open=collision]').click();
 const fill=async(key,value)=>{await page.locator('#number-'+key).fill(String(value));await page.locator('#number-'+key).press('Tab');};
 const metric=async label=>page.evaluate(label=>[...document.querySelectorAll('.metric')].find(e=>e.querySelector('span').textContent===label)?.querySelector('strong').textContent,label);
 check('动量动能单位及四位有效数字保留尾零',(await metric('碰前总动量 P'))==='1.000kg·m/s'&&(await metric('碰后总动量 P'))==='1.000kg·m/s'&&(await metric('碰前总动能 K'))==='5.500J');
 check('四位有效数字覆盖小数、科学计数法和零',await page.evaluate(()=>collisionNumber(.000012346)==='0.00001235'&&collisionNumber(12345)==='1.235e+4'&&collisionNumber(0)==='0.000'&&collisionNumber(-0)==='0.000'));
 await fill('mass1',0);check('零质量被拒绝并提示',await page.evaluate(()=>state.p.mass1===1&&document.querySelector('#scienceNotice').textContent.includes('大于 0')));
 await fill('mass2',-1);check('负质量被拒绝',await page.evaluate(()=>state.p.mass2===2));
 await fill('e',-1);check('恢复系数下界限定为 0',await page.evaluate(()=>state.p.e===0));await fill('e',2);check('恢复系数上界限定为 1',await page.evaluate(()=>state.p.e===1));
 await page.locator('[data-preset="0"]').click();check('等质量弹性预设交换速度且动能不变',await page.evaluate(()=>{const r=SCIENCE.collisionSolution(state.p);return r.after.v1===-1&&r.after.v2===3&&r.energyLoss===0;}));
 await page.locator('[data-action=play]').click();await page.waitForFunction(()=>state.time>SCIENCE.collisionSolution(state.p).collisionTime+.1);await page.locator('[data-action=play]').click();
 check('实际播放跨过碰撞事件，速度切换且球不穿透',await page.evaluate(()=>{const a=SCIENCE.collisionState(state.p,state.time);return a.collided&&a.v1===-1&&a.v2===3&&a.x2-a.x1>=.5;}));
 const time=await page.evaluate(()=>state.time);await page.locator('#science-graph').selectOption('position');await page.waitForFunction(()=>stageInfo?.graph?.key==='position');
 check('切换到位置时间图保留当前时刻',await page.evaluate(t=>state.time===t&&stageInfo.graph.key==='position',time));
 await page.locator('[data-action=collision-start]').click();check('回到开始保留参数',await page.evaluate(()=>state.time===0&&state.p.mass2===1&&state.p.graph==='position'));
 await page.locator('[data-action=collision-contact]').click();check('跳转精确碰撞时刻，位置连续且直接显示碰后速度',await page.evaluate(()=>{const r=SCIENCE.collisionSolution(state.p),a=SCIENCE.collisionState(state.p,state.time);return state.time===r.collisionTime&&a.collided&&Math.abs(a.x2-a.x1-.5)<1e-12;}));
 await page.locator('#timeline').focus();await page.keyboard.press('End');check('时间条可到末端且显示结束状态',await page.evaluate(()=>state.time===collisionDuration(state.p)&&!state.running)&&await page.locator('#simulationStatus').innerText()==='演示结束');
 await page.locator('[data-action=play]').click();await page.waitForFunction(()=>state.running&&state.time<.5);await page.locator('[data-action=play]').click();check('末端点击播放重新开始',await page.evaluate(()=>state.time<.5));
 await page.locator('#timeline').focus();await page.keyboard.press('Home');check('时间条可退回碰前',await page.evaluate(()=>state.time===0&&!SCIENCE.collisionState(state.p,state.time).collided));
 await page.locator('[data-action=step]').click();check('单步推进 0.05 s',await page.evaluate(()=>state.time===.05));
 await fill('u1',4);check('修改物理参数暂停并从初始位置开始',await page.evaluate(()=>state.time===0&&!state.running)&&await page.locator('#simulationStatus').innerText()==='已暂停');
 await page.locator('[data-preset="1"]').click();await page.locator('[data-action=collision-contact]').click();await page.locator('[data-action=step]').click();
 check('e=0 后同速共同运动，动能减少',await page.evaluate(()=>{const r=SCIENCE.collisionSolution(state.p),a=SCIENCE.collisionState(state.p,state.time);return a.collided&&a.v1===a.v2&&Math.abs(a.x2-a.x1-.5)<1e-12&&r.energyLoss>0&&r.after.kinetic<r.before.kinetic;}));
 check('e=0 与非等质量时显示守恒差为零',(await metric('总动量差 ΔP'))==='0.000kg·m/s'&&(await metric('当前阶段'))==='碰后共同运动');
 await page.locator('[data-preset="2"]').click();check('同向追赶也会碰撞',await page.evaluate(()=>state.p.u1>state.p.u2&&state.p.u2>0&&SCIENCE.collisionSolution(state.p).collides));
 await page.locator('[data-preset="3"]').click();check('不相遇提示、禁用跳转且不伪造碰后读数',await page.locator('#scienceNotice').innerText().then(t=>t.includes('不会碰撞'))&&await page.locator('[data-action=collision-contact]').isDisabled()&&(await metric('碰后总动能 K'))==='—J');
 await page.locator('[data-action=play]').click();await page.waitForFunction(()=>state.time>.1);await page.locator('[data-action=play]').click();check('不相遇时仍可观察各自匀速运动',await page.evaluate(()=>{const a=SCIENCE.collisionState(state.p,state.time);return a.x1< -3&&a.x2>3&&!a.collided;}));
 await fill('u1',2);await fill('u2',2);check('同速不会碰撞',await page.locator('#formulaCaption').innerText().then(t=>t.includes('不会碰撞')));
 await fill('u1',0);await fill('u2',0);check('两球静止时所有读数有限',await page.locator('#metrics').innerText().then(t=>!(/NaN|Infinity/.test(t))));
 await fill('u1',1.0000000001);await fill('u2',1);await page.locator('[data-action=collision-contact]').click();await page.waitForTimeout(80);check('很慢的追赶可直接跳到碰撞且图表有限',await page.evaluate(()=>state.time>1e10&&Number.isFinite(stageInfo.current.x1)&&stageInfo.current.collided));
 await page.locator('[data-preset="1"]').click();await fill('e',.4567890123);await page.locator('#science-graph').selectOption('position');
 await page.locator('[data-action=save]').click();await page.locator('#classTitle').fill('碰撞回归');await page.locator('[data-action=confirm-save]').click();await page.evaluate(()=>showLibrary('classes'));await page.locator('[data-class-open]').first().click();
 check('保存课堂恢复恢复系数精度和图表类型',await page.evaluate(()=>state.model.id==='collision'&&state.p.e===.4567890123&&state.p.graph==='position'&&state.time===0));
 await page.locator('[data-action=share]').click();const download=page.waitForEvent('download');await page.locator('[data-action=export-config]').click();await(await download).saveAs(path.join(out,'collision-config.json'));await page.locator('[data-action=close-dialog]').click();
 await page.locator('#importFile').setInputFiles(path.join(out,'collision-config.json'));await page.locator('[data-action=confirm-import]').click();check('version:1 配置实际导出导入',JSON.parse(fs.readFileSync(path.join(out,'collision-config.json'))).version===1&&await page.evaluate(()=>state.p.graph==='position'&&state.p.e===.4567890123));
 check('非法导入质量限制到正值，旧配置兼容',await page.evaluate(()=>safeParams(modelById('collision'),{mass1:0,mass2:-3,e:2}).mass1===.1&&safeParams(modelById('collision'),{mass2:-3}).mass2===.1&&validateImport({app:'zhixiang',version:1,type:'model',model:'pendulum',params:{length:2}}).params.length===2));
 await page.locator('[data-action=collision-contact]').click();await page.waitForTimeout(60);await page.screenshot({path:path.join(out,'collision-position.png'),fullPage:true});
 const values=await page.evaluate(()=>JSON.stringify(collisionReadout(state.p).metrics));
 for(const width of[320,390,768,1024,1440]){
  await page.setViewportSize({width,height:1000});await page.waitForTimeout(100);
  check(`${width}px 无横向溢出且数值不随窗口改变`,await page.evaluate(v=>document.documentElement.scrollWidth<=innerWidth+1&&JSON.stringify(collisionReadout(state.p).metrics)===v,values));
  if(width===390)await page.screenshot({path:path.join(out,'collision-mobile.png'),fullPage:true});
 }
 await page.locator('#science-graph').selectOption('velocity');await page.waitForTimeout(80);await page.screenshot({path:path.join(out,'collision-velocity.png'),fullPage:true});
 const config=await page.evaluate(()=>JSON.stringify(state.p));await page.locator('[data-action=ink]').click();const box=await page.locator('#annotation').boundingBox();await page.mouse.move(box.x+70,box.y+70);await page.mouse.down();await page.mouse.move(box.x+110,box.y+100,{steps:5});await page.mouse.up();
 check('板书保留且不改变碰撞参数',await page.evaluate(c=>state.strokes.length===1&&JSON.stringify(state.p)===c,config));await page.locator('[data-action=ink]').click();
 const png=page.waitForEvent('download');await page.locator('[data-action=screenshot]').click();await(await png).saveAs(path.join(out,'collision-export.png'));check('实际导出含公式读数与板书的 PNG',fs.statSync(path.join(out,'collision-export.png')).size>20000);
 await page.locator('[data-action=present]').click();check('大屏模式可用',await page.locator('body').evaluate(e=>e.classList.contains('presenting')));await page.keyboard.press('Escape');await page.evaluate(()=>exitPresentation());
 await page.locator('.model-question summary').click();await page.locator('#answerButton').click();check('讨论问题与解答可展开',await page.locator('#answerText').isVisible()&&await page.locator('#answerText').innerText().then(t=>t.includes('动能')));
 const offline=await context.newPage(),requests=[];offline.on('pageerror',e=>errors.push(e.message));offline.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await offline.goto('file://'+path.join(root,'standalone.html')+'#model=collision');await offline.waitForTimeout(100);
 check('单文件包含碰撞模型且离线无网络请求',await offline.locator('h1').innerText()==='碰撞与动量守恒'&&requests.length===0,requests);
 check('分文件版无远程运行依赖',remote.length===0,remote);check('浏览器无脚本异常',errors.length===0,errors);
 await browser.close();fs.writeFileSync(path.join(out,'collision-browser-results.json'),JSON.stringify({date:new Date().toISOString(),results,errors},null,2));console.log(`RESULT ${results.filter(r=>r.passed).length}/${results.length}`);if(results.some(r=>!r.passed))process.exitCode=1;
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
