// Generated by build.py from models/manifest.json.
export const MODELS = Object.freeze([
  {
    "id": "solids",
    "cat": "math",
    "title": "常见几何体"
  },
  {
    "id": "sections",
    "cat": "math",
    "title": "正方体截面"
  },
  {
    "id": "nets",
    "cat": "math",
    "title": "展开与折叠"
  },
  {
    "id": "parabola",
    "cat": "math",
    "title": "二次函数与抛物线"
  },
  {
    "id": "functions",
    "cat": "math",
    "title": "函数图像与变换"
  },
  {
    "id": "conics",
    "cat": "math",
    "title": "圆锥曲线"
  },
  {
    "id": "derivative",
    "cat": "math",
    "title": "导数与切线"
  },
  {
    "id": "solar",
    "cat": "geography",
    "title": "太阳高度角与日影"
  },
  {
    "id": "gas",
    "cat": "physics",
    "title": "理想气体与分子运动"
  },
  {
    "id": "projectile",
    "cat": "physics",
    "title": "平抛与斜抛运动"
  },
  {
    "id": "pendulum",
    "cat": "physics",
    "title": "单摆与能量转化"
  },
  {
    "id": "trig",
    "cat": "math",
    "title": "单位圆与三角函数"
  },
  {
    "id": "wave",
    "cat": "physics",
    "title": "波的传播与振动"
  },
  {
    "id": "refraction",
    "cat": "physics",
    "title": "光的折射与全反射"
  },
  {
    "id": "lens",
    "cat": "physics",
    "title": "透镜成像"
  },
  {
    "id": "spring",
    "cat": "physics",
    "title": "弹簧振子与简谐运动"
  },
  {
    "id": "induction",
    "cat": "physics",
    "title": "电磁感应"
  },
  {
    "id": "double-slit",
    "cat": "physics",
    "title": "双缝干涉"
  },
  {
    "id": "collision",
    "cat": "physics",
    "title": "碰撞与动量守恒"
  },
  {
    "id": "circular",
    "cat": "physics",
    "title": "圆周运动与向心力"
  },
  {
    "id": "electric",
    "cat": "physics",
    "title": "电场线与等势线"
  },
  {
    "id": "seasons",
    "cat": "geography",
    "title": "地球公转与四季"
  }
]);
